added liquibase script: event, image, event_type
Clasker1/exadel_sandbox pull request #1
Opened 2021-03-26 08:51 UTC by VadimBlagiy

2021-03-26 09:55 UTC, Clasker1 commented on sandbox-backend/src/main/resources/db/changelog/changes/2021.03.26_create_table_blagiy.yml
> +databaseChangeLog:
Нужно поменять порядок создания таблиц, в начале делаем таблицы, на которые нет зависимостей (image, event_type), потом уже event ( c зависимостями на image и event_type)

2021-03-26 11:02 UTC, ikantsevich commented on sandbox-backend/src/main/resources/db/changelog/changes/2021.03.26_create_table_blagiy.yml
> +                  constraints:
Do we sure that all columns are not null?

2021-03-26 12:35 UTC, VadimBlagiy commented
- column:
                  name: EV_SHORT_DESCRIPTION
                  type: VARCHAR(250)
                  constraints:
                    nullable: false             

I think so. This is  really necessary field to fill! It shouldn't be left empty. Or am I wrong?

2021-03-29 14:08 UTC, Clasker1 requested changes

2021-03-29 14:08 UTC, Clasker1 commented on sandbox-backend/src/main/resources/db/changelog/changes/create-demo-table.yaml
> +  - changeSet:
Please remove this changeset. I've already merged similar that should drop demo table

2021-03-29 14:08 UTC, Clasker1 commented on sandbox-web/src/main/resources/application.properties
> -server.port=8080
Lets use 8085, or just remove this change from PR

2021-03-29 14:13 UTC, Clasker1 commented on sandbox-backend/src/main/resources/db/changelog/changes/2021.03.26_create_table_blagiy.yml
> +                  name: IMG_CREATED_AT
Its good practice to use ```defaultValue: now()``` for create at fields.

2021-03-29 15:48 UTC, Clasker1 requested changes

2021-03-29 17:32 UTC, merged